# Generated by Django 2.2.4 on 2019-08-01 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180226_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='projecturl',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
